
import type { Bike, User, Rental } from './types';
import { addDays, subDays, subMonths, subYears, startOfMonth, startOfQuarter, startOfYear } from 'date-fns';

const now = new Date();

export const MOCK_USERS: User[] = [
  {
    id: 'user1',
    email: 'renter@motorent.com', // Changed from vroomvroom.vn for staff access test
    name: 'Alice Wonderland',
    role: 'renter',
    avatarUrl: 'https://placehold.co/100x100.png',
    lastLogin: subDays(now, 2),
    feedbackCount: 3,
    dateOfBirth: '1990-05-15',
    address: '123 Main St, Wonderland',
    credentialIdNumber: 'CW1234567',
    credentialIdImageUrl: undefined,
    createdAt: startOfMonth(now), // This month
  },
  {
    id: 'user2',
    email: 'admin@motorent.com', // Changed from vroomvroom.vn
    name: 'Bob The Builder',
    role: 'admin',
    avatarUrl: 'https://placehold.co/100x100.png',
    lastLogin: subDays(now, 1),
    feedbackCount: 0,
    dateOfBirth: '1985-10-20',
    address: '456 Tool Ave, Build City',
    credentialIdNumber: undefined,
    credentialIdImageUrl: undefined,
    createdAt: subMonths(startOfQuarter(now), 1), // Previous quarter
  },
  {
    id: 'user3',
    email: 'staff@motorent.com', // This is the one for testing staff access
    name: 'Charlie Brown',
    role: 'staff',
    avatarUrl: 'https://placehold.co/100x100.png',
    lastLogin: now,
    feedbackCount: 1,
    dateOfBirth: '1995-02-10',
    address: '789 Comic Strip, Peanuts Town',
    credentialIdNumber: undefined,
    credentialIdImageUrl: undefined,
    createdAt: subMonths(now, 2), // This quarter (if current month > 2 months from quarter start)
  },
  {
    id: 'user4',
    email: 'new.renter@example.com',
    name: 'Diana Prince',
    role: 'renter',
    avatarUrl: 'https://placehold.co/100x100.png',
    lastLogin: subDays(now, 5),
    feedbackCount: 0,
    dateOfBirth: '1980-03-22',
    address: '1 Justice Way, Themyscira',
    credentialIdNumber: 'AMZ987654',
    credentialIdImageUrl: undefined,
    createdAt: subYears(startOfYear(now),1), // Last year
  },
  {
    id: 'user5',
    email: 'early.bird@example.com',
    name: 'Early Bird',
    role: 'renter',
    avatarUrl: 'https://placehold.co/100x100.png',
    lastLogin: subDays(now, 10),
    feedbackCount: 2,
    dateOfBirth: '1975-01-01',
    address: '1 Dawn Rd, Sun City',
    credentialIdNumber: 'EB0000001',
    credentialIdImageUrl: undefined,
    createdAt: subMonths(now, 5), // This year, but potentially not this quarter
  },
];

export const MOCK_BIKES: Bike[] = [
  {
    id: 'bike1',
    name: 'Urban Sprinter Z250',
    type: 'Scooter',
    imageUrl: 'https://placehold.co/600x400.png" data-ai-hint="scooter city',
    pricePerDay: 45,
    description: 'Navigate the city streets with ease on this agile and fuel-efficient scooter. Perfect for daily commutes and quick errands.',
    features: ['Automatic Transmission', 'ABS', 'LED Headlights', 'USB Charger', 'Under-seat Storage'],
    location: 'Downtown Central',
    rating: 4.5,
    isAvailable: true,
    amount: 10,
    cylinderVolume: 249,
  },
  {
    id: 'bike2',
    name: 'Adventure Pro 500X',
    type: 'Adventure',
    imageUrl: 'https://placehold.co/600x400.png" data-ai-hint="adventure motorcycle',
    pricePerDay: 75,
    description: 'Conquer any terrain with this rugged adventure bike. Equipped for long journeys and off-road exploration.',
    features: ['Manual 6-Speed', 'Switchable ABS', 'Spoke Wheels', 'Luggage Racks', 'Windscreen'],
    location: 'Mountain Pass Rentals',
    rating: 4.8,
    isAvailable: true,
    amount: 5,
    cylinderVolume: 471,
  },
  {
    id: 'bike3',
    name: 'Speedster R1000',
    type: 'Sport',
    imageUrl: 'https://placehold.co/600x400.png" data-ai-hint="sport motorcycle',
    pricePerDay: 120,
    description: 'Experience thrilling performance with this high-powered sportbike. Precision handling and blistering acceleration.',
    features: ['Manual 6-Speed', 'Quick Shifter', 'Traction Control', 'Full Fairing', 'Performance Exhaust'],
    location: 'Speedway Rentals Co.',
    rating: 4.9,
    isAvailable: false,
    amount: 3,
    cylinderVolume: 999,
  },
  {
    id: 'bike4',
    name: 'Classic Rider V-Twin',
    type: 'Cruiser',
    imageUrl: 'https://placehold.co/600x400.png" data-ai-hint="classic motorcycle',
    pricePerDay: 90,
    description: 'Ride in style with this iconic V-twin cruiser. Timeless design combined with modern comfort for the open road.',
    features: ['Manual 5-Speed', 'Chrome Accents', 'Leather Saddlebags', 'Comfort Seat', 'Loud Pipes'],
    location: 'Route 66 Motorbikes',
    rating: 4.7,
    isAvailable: true,
    amount: 7,
    cylinderVolume: 1200,
  },
  {
    id: 'bike5',
    name: 'EcoVolt Commuter',
    type: 'Electric',
    imageUrl: 'https://placehold.co/600x400.png" data-ai-hint="electric scooter',
    pricePerDay: 55,
    description: 'Silent, eco-friendly, and zippy. The ideal electric scooter for sustainable urban mobility.',
    features: ['Automatic', 'Regenerative Braking', 'Digital Display', 'Removable Battery', 'Quiet Operation'],
    location: 'GreenWheels Hub',
    rating: 4.3,
    isAvailable: true,
    amount: 12,
  },
  {
    id: 'bike6',
    name: 'CityHopper 125',
    type: 'Scooter',
    imageUrl: 'https://placehold.co/600x400.png" data-ai-hint="small scooter',
    pricePerDay: 35,
    description: 'A nimble and affordable 125cc scooter for zipping through city traffic.',
    features: ['Automatic', 'Lightweight', 'Fuel Efficient'],
    location: 'Downtown Central',
    rating: 4.1,
    isAvailable: true,
    amount: 8,
    cylinderVolume: 125,
  },
  {
    id: 'bike7',
    name: 'Tourer Max 750',
    type: 'Adventure',
    imageUrl: 'https://placehold.co/600x400.png" data-ai-hint="touring motorcycle',
    pricePerDay: 85,
    description: 'Comfortable and capable tourer for long distance rides with ample storage.',
    features: ['Manual 6-Speed', 'Heated Grips', 'Large Panniers', 'Comfort Seat'],
    location: 'Mountain Pass Rentals',
    rating: 4.6,
    isAvailable: true,
    amount: 4,
    cylinderVolume: 749,
  },
];


export const MOCK_RENTALS: Rental[] = [
  {
    id: 'rental1',
    bikeId: 'bike1',
    userId: 'user1',
    startDate: addDays(new Date(), -10),
    endDate: addDays(new Date(), -7),
    totalPrice: 45 * 3,
    options: ['helmet'],
    status: 'Completed',
    bikeName: MOCK_BIKES.find(b => b.id === 'bike1')!.name,
    bikeImageUrl: MOCK_BIKES.find(b => b.id === 'bike1')!.imageUrl,
    orderDate: addDays(new Date(), -12),
  },
  {
    id: 'rental2',
    bikeId: 'bike2',
    userId: 'user1',
    startDate: addDays(new Date(), 2),
    endDate: addDays(new Date(), 5),
    totalPrice: 75 * 3,
    options: ['helmet', 'insurance'],
    status: 'Upcoming',
    bikeName: MOCK_BIKES.find(b => b.id === 'bike2')!.name,
    bikeImageUrl: MOCK_BIKES.find(b => b.id === 'bike2')!.imageUrl,
    orderDate: addDays(new Date(), -1),
  },
  {
    id: 'rental3',
    bikeId: 'bike4',
    userId: 'user1',
    startDate: addDays(new Date(), -30),
    endDate: addDays(new Date(), -25),
    totalPrice: 90 * 5,
    options: ['helmet', 'saddlebags'],
    status: 'Completed',
    bikeName: MOCK_BIKES.find(b => b.id === 'bike4')!.name,
    bikeImageUrl: MOCK_BIKES.find(b => b.id === 'bike4')!.imageUrl,
    orderDate: addDays(new Date(), -32),
  },
];

export const RENTAL_OPTIONS = [
  { id: 'helmet', name: 'Helmet', price: 5, selected: false },
  { id: 'insurance', name: 'Full Coverage Insurance', price: 15, selected: false },
  { id: 'gps', name: 'GPS Navigation', price: 10, selected: false },
  { id: 'luggage', name: 'Side Luggage Panniers', price: 12, selected: false },
];
